### ISSUE TITLE
Deployer never succeed when there is a lot of tx/s

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-sc-toolkit#119]
**Describe the bug**
When we have more than 500 tx/s that are smart contract calls and each one generate an event, it charge the event store of the node that keep only the latest 10k events. So when someone want to use the deployer that wait for finality before fetching the event he nerver fetch the deploy event and so block.

**To Reproduce**

1. Use the deployer
2. Deploy
3. Wait

**Expected behavior**
The SC is deployed and we have the address displayed

**Screenshots**
https://discord.com/channels/828270821042159636/1077141599236132914/1077141599236132914

**Versions**
dev

**Additional context**
I think it could be possible to use the polling of events to get the event before the finality and wait for finality afterwards.

**Comment by BatiGencho** [comment]
Lined PR solving this problem: https://github.com/massalabs/massa-sc-toolkit/pull/121

**Comment by gregLibert** [comment]
This issue also impacts. cc @SlnPons
