### ISSUE TITLE
Specify the expected parameter "fee" when using deploySC

### ISSUE THREAD

**Issue by leoloco** [massalabs/massa-sc-toolkit#120]
**Context**
When deploying a smart contract using the deploySC, we can specify a parameter "fee". While I can see that the expected type is a number, it is unclear to me what fee amount would correspond to in Massa. Is it a 1:1 ratio (1 unit of fee equals 1 Massa token) or is it expressed in an other unit/ratio ?

**User flow**
Create a smart contract project as in https://github.com/massalabs/massa-sc-toolkit/blob/main/packages/sc-project-initializer/commands/init/README.md, build and run the deploySC with :
`npm run deploy`

**Comment by leoloco** [comment]
@massalabs/run

**Comment by BatiGencho** [comment]
I suggest an elegant solution using this MR first: https://github.com/massalabs/massa-web3/pull/109 then merging in the changes into the toolkit wrapper.

**Comment by damip** [comment]
The dev experience should be unified with https://github.com/massalabs/as/blob/main/packages/as-types/assembly/amount.ts
