### ISSUE TITLE
remove unnecessary lines

### ISSUE THREAD

**Issue by lilyanB** [massalabs/massa-sc-toolkit#135]
**Context**
I use this toolkit to setup project. When the project is setup, I see a dead code can be remove

**How to**
I just run the command "npx clear-npx-cache && npx @massalabs/sc-project-initializer@dev init my-sc"

**Technical details**
In this files:
"as-pect.config.js"

wee have these unnecessary lines(22 and 23):
```js
  /** Enable code coverage. */
  // coverage: ["assembly/**/*.ts"],
```

**Comment by Ben-Rey** [comment]
Not really useless as someone would want to use the coverage
