### ISSUE TITLE
Deploy: Deserialization error

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-sc-toolkit#146]
**Describe the bug**
*A clear and concise description of what the bug is.*

Deployment fail with error bellow when trying to deploy a DNS contract on the builder net

**To Reproduce**
*Steps to reproduce the behavior*

```
npx clear-npx-cache
npx @massalabs/sc-project-initializer@dev init deploy-dns
cd deploy-dns
npm run deploy
```

**Expected behavior**

I expect the contract to be deployed 

**Versions**
*The versions of software and packages the bug in present in (massa-as-sdk, toolkit, Thyra, web browser...)*

https://buildernet.massa.net/api/v2 (version DEVN.21.0)
@massalabs/as-transformer: 0.1.3-dev.20230207083744
@massalabs/as-types: 0.0.3-dev.20230207083744
@massalabs/massa-as-sdk: 2.0.2-dev.20230406132337
@massalabs/massa-sc-compiler: 0.0.4-dev.20230207082550
@massalabs/massa-sc-deployer: 0.0.4-dev.20230505100640
@massalabs/massa-web3: 1.16.2-dev.20230504131619

**Additional context**
*Add any other context about the problem here.*

```
npm run deploy   

> my-massa-sc@0.0.1 deploy
> npm run build && ts-node src/deploy.ts


> my-massa-sc@0.0.1 build /Users/nathanmassa/dev/test-toolkit/deploy-dns
> npx massa-as-compile

3 files to compile
contract to compile assembly/contracts/run.ts

contract to compile assembly/contracts/main.ts

contract to compile assembly/contracts/dns.ts

Wallet Address: AU1MPDRXuR22mwYDFCeZUDgYjcTAF1co6xujx2X6ugoHeYeGY3B5 has balance (candidate, final) = (499.98975, 499.98975)
Sending operation with 100000000 MAS coins...
Error: Models error: Deserialization error: Parsing Error: Failed Operation deserialization / Failed op deserialization / Failed OperationType deserialization / Failed ExecuteSC deserialization / Failed data deserialization / Failed Vec<u8> deserialization / Failed u64 deserialization / Fail / Input: [128, 194
```

**Comment by bilboquet** [comment]
@Thykof 
if it's possible for you try to remove massa-node/storage/cache/* and let me know please

**Comment by qdrn** [comment]
Are you using the builder net ? Asking because the step to deploy on buildernet is not detailed in how to reproduce section.

**Comment by qdrn** [comment]
https://buildernet.massa.net/api/v2 (version DEVN.21.0) > this should be changed to buildnet and not buildERnet.

**Comment by Thykof** [comment]
> if it's possible for you try to remove massa-node/storage/cache/* and let me know please

I was deploying on buildnet so I think I can't but I will retry on a local testnet22 sandbox node



> Are you using the builder net ? Asking because the step to deploy on buildernet is not detailed in how to reproduce section.

yes buildnet:

`.env` file content:
```
WALLET_PRIVATE_KEY="S..."

JSON_RPC_URL_PUBLIC=https://buildernet.massa.net/api/v2

```

**Comment by Thykof** [comment]
@Ben-Rey told me it's probably about max_coins parameter, so I will try:

- on a testnet22 local node
- downgrade sc-deployer version and try on buildnet21

**Comment by Ben-Rey** [comment]
for testnet 21 maybe try this version of deployer :[0.0.4-dev.20230406134443](https://www.npmjs.com/package/@massalabs/massa-sc-deployer/v/0.0.4-dev.20230406134443)

**Comment by Ben-Rey** [comment]
You must also downgrade web3 i think because Args object will be differents and you need it in deploySC

**Comment by Thykof** [comment]
It works with this version of massa-web3: 1.16.2-dev.20230425161033
