### ISSUE TITLE
Test smart contract - Sandbox

### ISSUE THREAD

**Issue by Trottoir** [massalabs/massa-sc-toolkit#16]
**The context**
Sc-developers test their contracts, and multiple-sc projects by running the local node. Allowing the Sandbox node in the Initializer, would cut the developer time of setting up the Sandbox node ([by following these instructions](https://docs.massa.net/en/latest/web3-dev/dummy-network-generation.html)).

**The need**
Ability to run the Sandbox node, in the project's environment initialized by the sc-initializer, with one line of code, in order to test the project's deployment, execution, all interactions, by being the master of the network. [Check here for reference](https://hardhat.org/hardhat-network/docs/guides/forking-other-networks). 

It allows creation of services [like this one](https://tryethernal.com/), which allow developers to visualize contract interactions in an explorer-like way.

**How-to**
- [ ] Automate the Sandbox-node running and create a tool allowing the one-command switch to Sandbox node.
- [ ] Write the documentation and Readme
- [ ] Add sandbox node execution to our procedures and CI practice if it makes sense
 
 
 **Technical details:**

**Q/A testing**

**Comment by longgamma-massa** [comment]
@Thykof recheck what needs to be done for the Sandbox node functionality in the sc-initializer, maybe we need to add more context

**Comment by longgamma-massa** [comment]
I'd prefer doing this without Thyra, in the Initializer, as a dependency option to run your Sandbox node in one-click (forking the mainnet's state to perform tests).
