### ISSUE TITLE
SC deployer should use a wallet file protected by password

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-sc-toolkit#20]
**The context:**
Priority: Must-have for the Mainnet

To deploy the SC via SC-Initializer, we must pass the private key to sign the ExecuteSC operation. At the moment, the private key is exposed in plain format in the env. file, which is okay for deploying in the Sandbox mode, but critical vulnerability for deploying on testnet/mainnet _(even on the testnet, it's not pretty safe since many users tend to use the same testnet address as the mainnet)._

**User-flow:**
1. Create a wallet-file where the encrypted private key is stored (note: discussion with dev necessary to determine best practices)
2. File is created and password to it assigned by user (check how it is done in Thyra for example)
3. 'npm run deploy' will ask for the password, in order to sign 
4. User enters the password
5. Check the password match and sign Operation, if successful
6. If password doesn't match -> display error message and allow 2 retries.

**How-to**
- Requires investigation of the best practices for encryption of the wallet's file contents.
- Possibility (nice-to-have) to sign operations with cold wallets like Ledger

**Technical details:**

**Q/A testing**

**Comment by longgamma-massa** [comment]
@Thykof @gregLibert I believe it has been solved atm but I need the confirmation from you

**Comment by Thykof** [comment]
No, it's not solved, the wallet provided to the deployer is a secret key in the .env file, in clear

**Comment by qdrn** [comment]
I think it makes sense to include that as an util on massa-web3 for instance as it can be used in the explorer for instance (for now it's broken now that the wallet is encoded).

**Comment by BatiGencho** [comment]
@Thykof @qdrn  @gregLibert  I had previously implemented a so called vault that did that in web3. It was used by the massa-wallet. Should I revive it ?

**Comment by Thykof** [comment]
@gregLibert the problem with the user flow you described is that if I want to deploy my contract in a CD Github Action, I would not be able to enter my password. In that case I would like to provide the private key as a Github Secret. Or, better, I provide as a Github Secret the password so that the deploy process can descrypt the wallet file without asking for the password but taking it from env vars.

@BatiGencho If that fit the needs I would say yes, having in mind that it might be great to describe the vault as a standard: https://github.com/massalabs/massa-standards/issues/13#issuecomment-1440256474

**Comment by gregLibert** [comment]
> @gregLibert the problem with the user flow you described is that if I want to deploy my contract in a CD Github Action, I would not be able to enter my password. In that case I would like to provide the private key as a Github Secret. Or, better, I provide as a Github Secret the password so that the deploy process can descrypt the wallet file without asking for the password but taking it from env vars.

I don't see why both ways shouldn't be possible :-)
