### ISSUE TITLE
Helper retrieving proto files from a specific address.

### ISSUE THREAD

**Issue by Elli610** [massalabs/massa-sc-toolkit#208]
( we3 ) Create a new helper that allow to retrieve proto files from a specific address

Todo
- Create a function that retrieve a proto file for a given smart contract
- Add a command allowing to run this function

related issue in massa-web3: https://github.com/massalabs/massa-web3/issues/264

**Comment by Ben-Rey** [comment]
The corresponding web3 issue should be referenced here
