### ISSUE TITLE
Problem when following smart contract documentation

### ISSUE THREAD

**Issue by deucalionn** [massalabs/massa-sc-toolkit#221]
**Describe the bug**
I was following the documentation of massa to create and deploy a basic smart-contract and i have a problem here ; https://docs.massa.net/en/latest/web3-dev/smart-contracts/getting-started.html#deploy-your-smart-contract

concretly i don't understand how i have to modify the line 26 of the deploy script ?
![image](https://github.com/massalabs/massa-sc-toolkit/assets/63683273/29ee7f8f-6321-459d-81ef-b61ea0aab0c3)

I was still able to successfully deploy the contract by manually entering the address in the code but I don't get the desired result as on the documentation.

i want this : 
![image](https://github.com/massalabs/massa-sc-toolkit/assets/63683273/b98101c1-9ccc-4cf8-bcc4-a835d0526fe4)

but i have this : 

![image](https://github.com/massalabs/massa-sc-toolkit/assets/63683273/d6f8e204-3f56-4d5a-aeca-a93ca362cdca)

**To Reproduce**

juste follow the documentation of creating and deploy smart-contract in massa.

**Expected behavior**
I expected to have as output the result of my sayHello function called by the constructor during deployment

**Versions**
last version

**Comment by Ben-Rey** [comment]
Hey! Happy to see that you're developing on Massa. We are currently improving the documentation so It will be clearer in the future. For now you can try this code in you deploy.ts

```typescript
import * as dotenv from 'dotenv';
import { readFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { deploySC, WalletClient, ISCData } from '@massalabs/massa-sc-deployer';
import { Args, IEvent, fromMAS } from '@massalabs/massa-web3';

dotenv.config();

const publicApi = process.env.JSON_RPC_URL_PUBLIC;
if (!publicApi) {
  throw new Error('Missing JSON_RPC_URL_PUBLIC in .env file');
}
const secretKey = process.env.WALLET_SECRET_KEY;
if (!secretKey) {
  throw new Error('Missing WALLET_SECRET_KEY in .env file');
}

const deployerAccount = await WalletClient.getAccountFromSecretKey(secretKey);

const __filename = fileURLToPath(import.meta.url);

const __dirname = path.dirname(path.dirname(__filename));

(async () => {
  let deployedInfo = await deploySC(
    publicApi,
    deployerAccount,
    [
      {
        data: readFileSync(path.join(__dirname, 'build', 'main.wasm')),
        coins: fromMAS(0.1),
        args: new Args().addString('Test'),
      } as ISCData,
    ],
    0n,
    4_200_000_000n,
    true,
  );

  // We need to wait for the contract to be deployed to get the address of the contract to call
  // in the constructor of the run contract

  let data = (deployedInfo.events?.find((e) => e.data) as IEvent).data;
  const address = data.split('Contract deployed at address:')[1].trim();

  deployedInfo = await deploySC(
    publicApi,
    deployerAccount,
    [
      {
        data: readFileSync(path.join(__dirname, 'build', 'run.wasm')),
        coins: fromMAS(0.1),
        args: new Args().addString(address).addString('Bob'),
      } as ISCData,
    ],
    0n,
    4_200_000_000n,
    true,
  );

  data = (deployedInfo.events?.find((e) => e.data) as IEvent).data;

  console.log(data);

  process.exit(0);
})();
```

**Comment by deucalionn** [comment]
Okay thank you for the response, so the run.ts is a smart-contract ? And why when i deploy my smart-contract the Event in the constructor don't appear in my console ? it's like when i deploy the main.wasm the constructor was not called...

**Comment by Ben-Rey** [comment]
Yes run is a smart contract. 
Which constructor are you talking about? Main file or Run file? 

Here is what I get if I deploy using the code I gave you before:
```
Sending operation with 100000000 MAS coins...
Operation successfully submitted with id: O12ekFADfuzwXtuiSMKiX8U4Y6Y5sisXEWYx63Tah6og3H73z7uT
Waiting for events...
Event Data Received: [
  {
    context: {
      slot: [Object],
      block: 'B1bvVGijVPLiVSRegY3NagcGcQW56RAhmraMLCHeWuq4xMC3bUx',
      read_only: false,
      index_in_slot: 0,
      call_stack: [Array],
      origin_operation_id: 'O12ekFADfuzwXtuiSMKiX8U4Y6Y5sisXEWYx63Tah6og3H73z7uT',
      is_final: false,
      is_error: false
    },
    data: 'Contract deployed at address: AS12r64PbwjDEiPDogcqzHKGj6itfw2hprs7XER99wmhw5DsLGaT3'
  }
]
Awaiting FINAL transaction status....
Transaction with Operation ID O12ekFADfuzwXtuiSMKiX8U4Y6Y5sisXEWYx63Tah6og3H73z7uT has reached finality!
Wallet Address: AU12NYgnnH5cfJuMdKCxQEBQM7eogJioCGN71G2bTUVujhr2Jbb6t has balance (candidate, final) = (477.75775, 477.75775)
Sending operation with 100000000 MAS coins...
Operation successfully submitted with id: O12UmzkZAHMxqtyCXcUnNBDYY7maFZ5mfy2UwsAPaAPfQPFbKtcE
Waiting for events...
Event Data Received: [
  {
    context: {
      slot: [Object],
      block: 'B1v1XLRpKnSdQF7C9wYJJtT1RoDWr1ACaRwSR1N2Q5iaU55ZYac',
      read_only: false,
      index_in_slot: 0,
      call_stack: [Array],
      origin_operation_id: 'O12UmzkZAHMxqtyCXcUnNBDYY7maFZ5mfy2UwsAPaAPfQPFbKtcE',
      is_final: false,
      is_error: false
    },
    data: 'Hello world! Greetings from Bob 👋'
  },
  {
    context: {
      slot: [Object],
      block: 'B1v1XLRpKnSdQF7C9wYJJtT1RoDWr1ACaRwSR1N2Q5iaU55ZYac',
      read_only: false,
      index_in_slot: 1,
      call_stack: [Array],
      origin_operation_id: 'O12UmzkZAHMxqtyCXcUnNBDYY7maFZ5mfy2UwsAPaAPfQPFbKtcE',
      is_final: false,
      is_error: false
    },
    data: 'Contract deployed at address: AS1FTwp5BydgAHWARxerVdBQENX9PpUE7TskAyiMC2LGn6tGNGGb'
  }
]
Awaiting FINAL transaction status....
Transaction with Operation ID O12UmzkZAHMxqtyCXcUnNBDYY7maFZ5mfy2UwsAPaAPfQPFbKtcE has reached finality!
```

**Comment by deucalionn** [comment]
I'm just trying to understand, run is a smart-contract who call another one ( main ) ? But if i have only main.ts and i want to develop a script who call it how can i do it ? sorry for all the questions ...

**Comment by Ben-Rey** [comment]
> I'm just trying to understand, run is a smart-contract who call another one ( main ) ? But if i have only main.ts and i want to develop a script who call it how can i do it ? sorry for all the questions ...

No worries you are right to ask.

I'm just trying to understand, run is a smart-contract who call another one ( main ) ?
Exactly, it's a way of calling a smart contract (by another smart contract)

But if i have only main.ts and i want to develop a script who call it how can i do it ?

When you talk about script I assume you talk about a js file.
If you want to call your smart-contract, you need to use massa-web3. https://www.npmjs.com/package/@massalabs/massa-web3

Here is an example on how a function of a smart contract can be called from a js file:
https://github.com/massalabs/massa-sc-examples/blob/main/age/html/js/index.js

**Comment by deucalionn** [comment]
thank you very much you have enlightened me. i will try to use massa-web3 to interact with my sc. ( im actually trying to implement FA2 method into massa smart-contract )

**Comment by Ben-Rey** [comment]
> thank you very much you have enlightened me. i will try to use massa-web3 to interact with my sc. ( im actually trying to implement FA2 method into massa smart-contract )

I'm glad I could help ! 
I think you'll find some inspiration here:
https://github.com/massalabs/massa-standards/tree/main/smart-contracts/assembly/contracts

**Comment by deucalionn** [comment]
Hi, it's me ( again ) I'm trying to call my smart-contract with massa-web3 but when i want to create client with baseAccount i have this error : Uncaught (in promise) Error: Account address not correspond the the address submitted
    at WalletClient.addAccountsToWallet (bundle.js:15210:23)
    at async WalletClient.setBaseAccount (bundle.js:15099:32)
    at async ClientFactory.createDefaultClient (bundle.js:13972:13) 
let massa = window.massa;

// create a base account for signing transactions
const baseAccount = {
    address: 'my-address',
    secretKey: 'my-secret-key',
    publicKey: 'my-public-key'
};
// get the secretKey with wallet_get_secret_key function

let client = null

const sc_addr = "AS1WjJmycSWF8gcnrHxjxHqp1c5aPSPLjHSiFQehRUdbyZtBP15B"

// initialize a testnet client
massa.ClientFactory.createDefaultClient(
    massa.DefaultProviderUrls.TESTNET,
    false,
    baseAccount
).then((c) => client = c);

console.log(client)

``

**Comment by Ben-Rey** [comment]
Hey can you try with this version of massa-web3: 1.19.0

**Comment by deucalionn** [comment]
Hi, caller() return the address of who call the function so if i use Coins.transferCoinsOf() and pass the returned value of caller() in "from" parametre will this work ? but i dont understand how the caller can autorize this transfer ? I am completely off track, aren't ?

**Comment by SlnPons** [comment]
Hey @deucalionn did you manage to do what you wanted? If the answer was satisfying, could you close this issue please? ;)
Help us to keep track and focus on the right things. 
Thanks a lot!
