### ISSUE TITLE
Fungible and non-fungible token factory - v1 implementation

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-sc-toolkit#24]
**The context**
The idea is to add a tool to generate a new FT or NFT by simply answering a few questions. In later stages such factories will be possible to use by non-devs, with a website deployed on Thyra to create FT and NFT in just a few clicks. 
This initial phase is to make it easier for SC-devs to create and deploy FT and NFT contracts in their Project.

**Use case:**
As a project creator, I need an NFT or FT contract to meet my needs.

**How-to:**
I use a simple project tool (perhaps like the project sc-initializer)
I answer simple yes/no questions
The tool itself generates a new project with the appropriate code containing the user's FT or NFT contract.

- [ ] Add a factory command that can be used to create or add a new SC template
- [ ] implement the Fungible token factory
- [ ] implement the Nonfungible token factory

**Comment by longgamma-massa** [comment]
Context, usecase, flow please @gregLibert :)

**Comment by gregLibert** [comment]
The idea is to add a tool to generate a new FT or NFT by simply answering a few questions.
 Use case:
As a project creator, I need an NFT or FT contract to meet my needs. 

To do this, :
- I use a simple project tool (perhaps like the project initializer)
- I answer simple yes/no questions

The tool itself generates a new project with the appropriate code containing the user's FT or NFT contract.

**Comment by longgamma-massa** [comment]
@Ben-Rey we will take this one :)

**Comment by SebastienValla** [comment]
https://github.com/massalabs/tokenFactory/pull/1

**Comment by SlnPons** [comment]
@gregLibert not sure what to do with the CR KO. Could you provide guidance please?

**Comment by SlnPons** [comment]
@longgamma-massa @gregLibert what are we doing with this ticket that is in KO for more than a month now? 
Please help to clean the board :)

**Comment by longgamma-massa** [comment]
It seems it's waiting for @peterjah approval on the https://github.com/massalabs/tokenFactory/pull/1, and we can close it? @SlnPons
