### ISSUE TITLE
add CD workflow for Massa-SC-toolkit and its dependencies

### ISSUE THREAD

**Issue by peterjah** [massalabs/massa-sc-toolkit#25]
TODO:

for @massalabs/as, @massalabs/massa-as-sdk and @massalabs/massa-sc-toolkit
- Setup projects CD
- publish dev version on npm
- remove imports from github  ( i.e https://gitpkg.now.sh/massalabs...)
- write some internal doc to explain the new development workflow

**Comment by Thykof** [comment]
We now have a CD workflow
