### ISSUE TITLE
Improve protobuf transformers

### ISSUE THREAD

**Issue by leoloco** [massalabs/massa-sc-toolkit#267]
**Context**
The team has recently implemented protobuf transformers for AS smart contracts. While this could greatly improve developer experience it is currently missing some features that make transformers difficult to use in real world settings

- [ ] Multi-files : Currently, protobuf transformers are only enabled for single-file use; It is currently not possible to use the transformers for a function that has been imported from another file. It would be nice if the transformers could be used with functions imported from other files. https://github.com/massalabs/as/issues/258
- [ ] u256/i256/i128/u128 : Currently, only standard AS types are supported. It would be great to support the previously mentioned types, especially for compatibility with EVM chains
- [ ] serializableObjects : same as above https://github.com/massalabs/as/issues/203

**Comment by qdrn** [comment]
cc @gregLibert
