### ISSUE TITLE
allow the functions to return arrays

### ISSUE THREAD

**Issue by bilboquet** [massalabs/massa-sc-toolkit#325]

**Comment by bilboquet** [comment]
depends on as[#304](https://github.com/massalabs/as/issues/304)

**Comment by bilboquet** [comment]
depends on as[#304](https://github.com/massalabs/as/issues/304)

@Elli610 I think this issue should be closed?

**Comment by Elli610** [comment]
> @Elli610 I think this issue should be closed?

yes !
