### ISSUE TITLE
fix "[Error: ENOENT: no such file or directory, open 'helpers/google/protobuf/descriptor.proto']

### ISSUE THREAD

**Issue by Elli610** [massalabs/massa-sc-toolkit#328]

**Comment by bilboquet** [comment]
to solve this issue we need to have access to `google/protobuf/descriptor.proto` on the cli side.

Given that this file is packaged with most of the "proto" tools (here `protoc`, on transformer side, and `protobufjs`, on cli side) 
I see 2 main ways:
1. understand and fix the dependencies in `massa-proto-cli` so the `descriptor.proto` bundled with `protobufjs` comes with the cli. But at this point I don't have any clue on how to do this (even if protobufjs is used by the cli it doesn't appear in `node_modules`)
2. on transformer side, add it to the list of `.proto` that have to be deployed with the SC so it is fetch with the `.proto` generated by the transformer.

So far, the second solution looks easier to me.
In the first place I see 
- one main drawback: `descriptor.proto` will get duplicated in the storage
- one advantage: the `descriptor.proto` from `protoc` and `protobufjs` I have locally differ significantly, at some point, with the first configuration one could face some incompatibilities which is not possible with the second one.

I'm going forward with the second solution but wish to ear form you @Ben-Rey @Elli610 @0xSwapFeeder @Eitu33 @damip

**Comment by Elli610** [comment]
> to solve this issue we need to have access to `google/protobuf/descriptor.proto` on the cli side.
> 
> Given that this file is packaged with most of the "proto" tools (here `protoc`, on transformer side, and `protobufjs`, on cli side) I see 2 main ways:
> 
> 1. understand and fix the dependencies in `massa-proto-cli` so the `descriptor.proto` bundled with `protobufjs` comes with the cli. But at this point I don't have any clue on how to do this (even if protobufjs is used by the cli it doesn't appear in `node_modules`)
> 2. on transformer side, add it to the list of `.proto` that have to be deployed with the SC so it is fetch with the `.proto` generated by the transformer.
> 
> So far, the second solution looks easier to me. In the first place I see
> 
> * one main drawback: `descriptor.proto` will get duplicated in the storage
> * one advantage: the `descriptor.proto` from `protoc` and `protobufjs` I have locally differ significantly, at some point, with the first configuration one could face some incompatibilities which is not possible with the second one.
> 
> I'm going forward with the second solution but wish to ear form you @Ben-Rey @Elli610 @0xSwapFeeder @Eitu33 @damip

Why don't we add the descriptor in the cli and when it detects a custom type, the descriptor will automatically be added in the output folder

**Comment by bilboquet** [comment]
Wip in #329
