### ISSUE TITLE
Handle custom types arrays in ts callers

### ISSUE THREAD

**Issue by Elli610** [massalabs/massa-sc-toolkit#340]

**Comment by Elli610** [comment]
not implemented in as-transformer yet

**Comment by bilboquet** [comment]
you should be able to try it using https://github.com/massalabs/as.git#326-array-of-integer-other-than-i32-or-u32-are-not-working
or directly with this SC AS1G75wsgo31KGLjQC4gUQmcfTfutzhkRutTijJ3w1fKeaVW1NJi (on buildnet)
