### ISSUE TITLE
Move tools to a npm package

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-sc-toolkit#36]
Move tools (compiler and deployer)

Issue: when a new version of the toolkit is released, a project created with the old version should be updated with the changes in the new toolkit release. But as for now the only way to update the Deployer class is by copy/paste and if the smart-contract developer has made some changes in this file, conflicts will appear. 

Solution: Move all the code needed to deploy a smart contract into a library that the project created with the toolkit will depend on, so that each time this library is updated, it's easy to benefit from the new version of the library with `npm update`. This *library* can be massa-web3 (because the current deployer use the client defined in massa-web3), massa-as-sdk, or massa-sc-toolkit.

**Comment by longgamma-massa** [comment]
Where is it moved (which repo?)?
