### ISSUE TITLE
Simplify how to build a SC different from default one

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-sc-toolkit#52]

**Comment by AurelienFT** [comment]
What I propose is that we define a typescript file at the root with code that will be append in the function that deploy the SCs

**Comment by gregLibert** [comment]
> What I propose is that we define a typescript file at the root with code that will be append in the function that deploy the SCs

Another approach could be to add an init function in the smart contract to be called  during deployment.

**Comment by AurelienFT** [comment]
Yes but it should be heavily documented and removable.

**Comment by gregLibert** [comment]
> Yes but it should be heavily documented and removable.


I'm not sure I understand your answer:
- documented => yes, we need to be better about this.
- removable => you develop your SC, if you use an exported init function, it will be called after scCreate, if there is no such exported function, nothing will be executed. So you don't need to delete anything. 

Unless you want to remove the init function from the smart contract storage after execution. In this case, we may be able to do that if we place the init function in a different bytecode in the SC bytecode storage and delete it after execution.

I have to admit that this notion of bytecode in the address object is still quite obscure for me, I would like to have an example to play with ...

**Comment by AurelienFT** [comment]
> * removable => you develop your SC, if you use an exported init function, it will be called after scCreate, if there is no such exported function, nothing will be executed. So you don't need to delete anything.

What I mean is that if we declare it by default in the SC in example to explain to the users this possibility we need to allow the user to delete this function and the deployer still works (to use less gas if not needed)
