### ISSUE TITLE
[BUG] Wasm file build

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/massa-sc-toolkit#53]
When we run npm run build, sometimes the wasm files inside the build/ folder are not being overwritten but instead the new binary content is appended to the old files.

**Comment by longgamma-massa** [comment]
@Thykof we should try to reproduce this, and check what happens

**Comment by Thykof** [comment]
I never experienced this, and we are compiling all the time. Since November the compiling process has changed.

@ASAPSegfault can you provide more context?
