### ISSUE TITLE
Create a temporary contract deployer

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-sc-toolkit#55]
Some SC are not for the posterity (hello world, sum ...).
We should create an optional deployer that can perform autoclean function using autonomous SC trigger.

**Comment by longgamma-massa** [comment]
@gregLibert need more context here... can it be done with the ExecuteSC?

**Comment by gregLibert** [comment]
> @gregLibert need more context here... can it be done with the ExecuteSC?

The idea is to have a kind of self-destructing smart contract deployer.

Usage scenario: I want to test the Massa blockchain and deploy a very simple smart contract. To reduce storage costs, it's best if my smart contract self-destructs to recover storage costs and only pay for gas costs.
