### ISSUE TITLE
Improve code boilerplate

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-sc-toolkit#70]
improve the examples that showcase sc development and test. 

Task: change all files in https://github.com/massalabs/massa-sc-toolkit/tree/main/commands/init/assembly

**Comment by longgamma-massa** [comment]
@Thykof do I need to test (and how)? :)

**Comment by Thykof** [comment]
@longgamma-massa you can read the changes here https://github.com/massalabs/massa-sc-toolkit/pull/72/files and see if its correct
