### ISSUE TITLE
Compiler not working

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-sc-toolkit#86]
**Describe the bug**

**To Reproduce**

run:
```
npx clear-npx-cache
npx @massalabs/sc-project-initializer@dev init testDir
cd testDir
npm run build
```

output:
```
> my-massa-sc@0.0.1 build
> npx massa-as-compile

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/massa-as-compile - Not found
npm ERR! 404 
npm ERR! 404  'massa-as-compile@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aurelienfoucault/.npm/_logs/2023-01-06T14_00_05_309Z-debug-0.log
```

**Expected behavior**
*A clear and concise description of what you expected to happen.*

This should create build folder and put wasm files into.

**Versions**
The versions of software and packages the bug in present in (massa-as-sdk, toolkit, Thyra, web browser...)

```
@massalabs/sc-project-initializer@0.1.2-dev.20230106132854
@massalabs/massa-sc-compiler@0.0.3-dev.20230106132854
```

**Additional context**

# Solution

We decided to extract the package massa-sc-compiler into a new repository: https://github.com/massalabs/massa-sc-compiler

**Comment by longgamma-massa** [comment]
This is a temporary fix to the issue when we created a monorepo. The package relationship with the Toolkit's sc-initializer should be taken into consideration in later stages and most likely reorganized.
