### ISSUE TITLE
Improve README of initializer

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-sc-toolkit#90]
I believe there are things that are missing in the README of the project initialised by the toolkit https://github.com/massalabs/massa-sc-toolkit/blob/main/packages/sc-project-initializer/commands/init/README.md. For instance it's not clear how to build and deploy other SCs than the main.ts. Also there are things that are hidden right now: the deploy command uses a SC to deploy the SC and so the main function will not be executed. I think this can be partly tackled in https://github.com/massalabs/massa-docs/issues/80 and refer to it.

Side note, in the README, `constructor` should point to the function in the code in the repo.

cc @Thykof

**Comment by Thykof** [comment]
@qdrn does this PR solve this issue: #91 ?

**Comment by qdrn** [comment]
I think this part is still not obvious: `Also there are things that are hidden right now: the deploy command uses a SC to deploy the SC and so the main function will not be executed.`. You don't necessarily have to tackle it here but I think it would be good to refer to docs.massa.net for more details (and put more details on docs.massa.net).

**Comment by Thykof** [comment]
I have opened a PR to improve documentation about deployment process and create this follow up issue about the sc-deployer documentation itself: https://github.com/massalabs/massa-sc-toolkit/issues/99
